/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Opciones para construir IR */
export interface BuildIrOptions {
  /** Tipo de fuente: "file", "db", "memory" */
  sourceType: string
  /** Formato: "json", "csv", "sqlite", etc. */
  format: string
  /** Path al archivo o base de datos */
  path?: string
  /** Configuración adicional en JSON */
  config?: string
}
/** Opciones para comparación */
export interface CompareOptions {
  /** Threshold de similitud (0.0 - 1.0) */
  threshold?: number
  /** Estrategia: "structural", "semantic", "hybrid" */
  strategy?: string
  /** Ignorar campos específicos */
  ignoreFields?: Array<string>
  /** Configuración adicional en JSON */
  config?: string
}
/** Opciones para proponer resolución */
export interface ResolveOptions {
  /** Estrategia: "conservative", "aggressive", "balanced" */
  strategy?: string
  /** Preferir fuente: "a", "b", "merge" */
  preferSource?: string
  /** Configuración adicional en JSON */
  config?: string
}
/** Opciones para aplicar resolución */
export interface ApplyOptions {
  /** Dry run (no aplicar cambios reales) */
  dryRun?: boolean
  /** Generar backup antes de aplicar */
  backup?: boolean
  /** Configuración adicional en JSON */
  config?: string
}
/** Construir IR desde una fuente */
export declare function buildIr(options: BuildIrOptions): Promise<string>
/** Comparar dos IRs */
export declare function compare(irAJson: string, irBJson: string, options?: CompareOptions | undefined | null): Promise<string>
/** Proponer plan de resolución */
export declare function proposeResolution(diffJson: string, options?: ResolveOptions | undefined | null): Promise<string>
/** Aplicar resolución */
export declare function applyResolution(planJson: string, options?: ApplyOptions | undefined | null): Promise<string>
/** Validar IR */
export declare function validateIr(irJson: string): Promise<string>
/** Versión del addon nativo */
export declare function version(): string
/** Función de prueba para verificar la conexión con Node */
export declare function ping(): string
/** Suma dos números (smoke test) */
export declare function add(a: number, b: number): number
