/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Opciones para construir IR */
export interface BuildIrOptions {
  /** Tipo de fuente: "file", "db", "memory" */
  sourceType: string
  /** Formato: "json", "csv", "sqlite", etc. */
  format: string
  /** Path al archivo o base de datos */
  path?: string
  /** Configuración adicional en JSON */
  config?: string
}
/** Opciones para comparación */
export interface CompareOptions {
  /** Threshold de similitud (0.0 - 1.0) */
  threshold?: number
  /** Estrategia: "structural", "semantic", "hybrid" */
  strategy?: string
  /** Ignorar campos específicos */
  ignoreFields?: Array<string>
  /** Configuración adicional en JSON */
  config?: string
}
/** Opciones para proponer resolución */
export interface ResolveOptions {
  /** Estrategia: "conservative", "aggressive", "balanced" */
  strategy?: string
  /** Preferir fuente: "a", "b", "merge" */
  preferSource?: string
  /** Configuración adicional en JSON */
  config?: string
}
/** Opciones para aplicar resolución */
export interface ApplyOptions {
  /** Dry run (no aplicar cambios reales) */
  dryRun?: boolean
  /** Generar backup antes de aplicar */
  backup?: boolean
  /** Configuración adicional en JSON */
  config?: string
}
/**
 * Construir IR desde una fuente
 *
 * # Argumentos
 * * `options` - Opciones de construcción
 *
 * # Returns
 * JSON string con la representación IR
 */
export declare function buildIr(options: BuildIrOptions): Promise<string>
/**
 * Comparar dos IRs
 *
 * # Argumentos
 * * `ir_a_json` - JSON del IR A
 * * `ir_b_json` - JSON del IR B
 * * `options` - Opciones de comparación
 *
 * # Returns
 * JSON string con el resultado de la diferencia
 */
export declare function compare(irAJson: string, irBJson: string, options?: CompareOptions | undefined | null): Promise<string>
/**
 * Proponer plan de resolución desde un diff
 *
 * # Argumentos
 * * `diff_json` - JSON del diff
 * * `options` - Opciones de resolución
 *
 * # Returns
 * JSON string con el plan de resolución
 */
export declare function proposeResolution(diffJson: string, options?: ResolveOptions | undefined | null): Promise<string>
/**
 * Aplicar un plan de resolución
 *
 * # Argumentos
 * * `plan_json` - JSON del plan
 * * `options` - Opciones de aplicación
 *
 * # Returns
 * JSON string con el resultado de la aplicación
 */
export declare function applyResolution(planJson: string, options?: ApplyOptions | undefined | null): Promise<string>
/**
 * Validar un IR JSON
 *
 * # Argumentos
 * * `ir_json` - JSON del IR a validar
 *
 * # Returns
 * JSON con resultado de validación { ok: bool, errors: string[] }
 */
export declare function validateIr(irJson: string): Promise<string>
/** Versión del addon nativo */
export declare function version(): string
/** Función de prueba para verificar la conexión con Node */
export declare function ping(): string
/** Suma dos números (smoke test) */
export declare function add(a: number, b: number): number
